M48
; DRILL file {KiCad (6.0.10)} date Tue Jan 10 00:37:09 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-10T00:37:09+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X54.356Y-27.442
X54.356Y-133.36
X161.29Y-27.442
X162.56Y-133.614
T0
M30
