M48
; DRILL file {KiCad (6.0.10)} date Wed Jan  4 19:46:44 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-04T19:46:44+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X54.356Y-27.442
X54.356Y-133.36
X161.29Y-27.442
X162.56Y-133.614
T0
M30
